### ISSUE TITLE
TypeError after run

### ISSUE THREAD

**Issue by JanickGers85** [adferrand/dnsrobocert#382]
Since I've upgraded to version 3.9.1 I encounter an error that hangs dnsrobocert silently.
I run the dockerized version.
Reverted to version 3.9.0, tomorrow I'll update this issue with the result of the next run.

Here the full log

```
2021-05-12 20:59:34 d9a9170daea1 dnsrobocert.core.main[1] INFO Exiting DNSroboCert.
2021-05-12 20:59:37 d9a9170daea1 dnsrobocert.core.main[1] INFO Starting DNSroboCert.
2021-05-12 20:59:37 d9a9170daea1 dnsrobocert.core.main[1] INFO Registering ACME account if needed.
2021-05-12 20:59:37 d9a9170daea1 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot register -n --user-agent-comment DNSroboCert/3.9.1 --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs -m ***@***.com --agree-tos --server https://acme-v02.api.letsencrypt.org/directory
----------
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
There is an existing account; registration of a duplicate account with this command is currently unsupported.
----------
2021-05-12 20:59:39 d9a9170daea1 dnsrobocert.core.main[1] INFO Creating missing certificates if needed (~1min for each)
2021-05-12 20:59:39 d9a9170daea1 dnsrobocert.core.main[1] INFO Handling the certificate for domain(s): ******
2021-05-12 20:59:39 d9a9170daea1 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot certonly -n --user-agent-comment DNSroboCert/3.9.1 --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs --manual --preferred-challenges=dns --manual-auth-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"******\"" --manual-cleanup-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"******\"" --expand --deploy-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"******\"" --server https://acme-v02.api.letsencrypt.org/directory --cert-name ****** -d ******
----------
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate for ******
Performing the following challenges:
dns-01 challenge for ******
Running manual-auth-hook command: /usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c "/tmp/tmp8yauys6w/dnsrobocert-runtime.yml" -l "******"
Output from manual-auth-hook command python:
Executing auth hook for domain ******, lineage ******.
Wait 30 seconds to let all challenges be propagated: ['_acme-challenge.******']

Waiting for verification...
Cleaning up challenges
Running manual-cleanup-hook command: /usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmp8yauys6w/dnsrobocert-runtime.yml" -l "******"
Output from manual-cleanup-hook command python:
Executing cleanup hook for domain ******, lineage ******.

Running deploy-hook command: /usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c "/tmp/tmp8yauys6w/dnsrobocert-runtime.yml" -l "******"
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/******/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/******/privkey.pem
   Your certificate will expire on ******. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again. To non-interactively renew *all* of your
   certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

----------
2021-05-12 21:00:24 d9a9170daea1 dnsrobocert.core.main[1] INFO Handling the certificate for domain(s): ******
2021-05-12 21:00:24 d9a9170daea1 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot certonly -n --user-agent-comment DNSroboCert/3.9.1 --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs --manual --preferred-challenges=dns --manual-auth-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"***\"" --manual-cleanup-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"***\"" --expand --deploy-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"***\"" --server https://acme-v02.api.letsencrypt.org/directory --cert-name *** -d ******
----------
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Cert not yet due for renewal
Keeping the existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
----------
2021-05-12 21:00:26 d9a9170daea1 dnsrobocert.core.main[1] INFO Handling the certificate for domain(s): ******
2021-05-12 21:00:26 d9a9170daea1 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot certonly -n --user-agent-comment DNSroboCert/3.9.1 --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs --manual --preferred-challenges=dns --manual-auth-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t auth -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"***\"" --manual-cleanup-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"***\"" --expand --deploy-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c \"/tmp/tmp8yauys6w/dnsrobocert-runtime.yml\" -l \"***\"" --server https://acme-v02.api.letsencrypt.org/directory --cert-name *** -d ******
----------
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Cert not yet due for renewal
Keeping the existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
----------
2021-05-12 21:00:28 d9a9170daea1 dnsrobocert.core.main[1] INFO Revoke and delete certificates if needed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/background.py", line 47, in run
    schedule.run_pending()
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
TypeError: _renew_job() missing 1 required positional argument: 'stop_thread'
```

Here my config.yaml

```
draft: false
acme:
  email_account: *****@*****.com
  staging: false
  certs_permissions:
    files_mode: 0777
    dirs_mode: 0777
profiles:
- name: MyProfile
  provider: ****
  provider_options:
    auth_token: **************************
certificates:
- name: ***
  domains:
  - ****
  profile: MyProfile
  force_renew: false
  deploy_hook: 'cp $(realpath /etc/letsencrypt/live/****/cert.pem) $(realpath /etc/****/cert.pem);cp $(realpath /etc/letsencrypt/live/****/chain.pem) $(realpath /etc/****/chain.pem);cp $(realpath /etc/letsencrypt/live/****/fullchain.pem) $(realpath /etc/****/fullchain.pem);cp $(realpath /etc/letsencrypt/live/****/privkey.pem) $(realpath /etc/****/privkey.pem)'
  domains:
  - ****
  profile: MyProfile
  force_renew: false
  deploy_hook: 'cp $(realpath /etc/letsencrypt/live/****/cert.pem) $(realpath /etc/****/cert.pem);cp $(realpath /etc/letsencrypt/live/****/chain.pem) $(realpath /etc/****/chain.pem);cp $(realpath /etc/letsencrypt/live/****/fullchain.pem) $(realpath /etc/****/fullchain.pem);cp $(realpath /etc/letsencrypt/live/****/privkey.pem) $(realpath /etc/****/privkey.pem)'
  domains:
  - ****
  profile: MyProfile
  force_renew: false
  deploy_hook: 'cp $(realpath /etc/letsencrypt/live/****/cert.pem) $(realpath /etc/****/cert.pem);cp $(realpath /etc/letsencrypt/live/****/chain.pem) $(realpath /etc/****/chain.pem);cp $(realpath /etc/letsencrypt/live/****/fullchain.pem) $(realpath /etc/****/fullchain.pem);cp $(realpath /etc/letsencrypt/live/****/privkey.pem) $(realpath /etc/****/privkey.pem)'
```

**Comment by JanickGers85** [comment]
Same error on docker version 3.9.0.
If i restart the image the process of renewal ends correctly, the next scheduled run report this error after successfully check all my 3 certs

```
2021-05-16 20:35:44 819c37ac9c26 dnsrobocert.core.main[1] INFO Revoke and delete certificates if needed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/background.py", line 47, in run
    schedule.run_pending()
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
TypeError: _renew_job() missing 1 required positional argument: 'stop_thread'
```

**Comment by JanickGers85** [comment]
Seems working with docker version 3.8.3 despite the warning about the renewal config, until I found out more or someone reply me on this issue :)

```
2021-05-18T05:42:39.315452562Z 2021-05-18 05:42:39 93e08b32bd47 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot renew -n --user-agent-comment DNSroboCert/3.8.3 --config-dir /etc/letsencrypt --deploy-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c \"/tmp/tmpx3yq_f19/dnsrobocert-runtime.yml\"" --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs
2021-05-18T05:42:39.315475695Z ----------
2021-05-18T05:42:40.495223606Z Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2021-05-18T05:42:40.497699680Z
2021-05-18T05:42:40.497730618Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:40.497737991Z Processing /etc/letsencrypt/renewal/domain1.conf
2021-05-18T05:42:40.497744343Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:40.499063255Z Attempting to parse the version 1.13.0 renewal configuration file found at /etc/letsencrypt/renewal/domain1.conf with version 1.10.1 of Certbot. This might not work.
2021-05-18T05:42:40.792301205Z Cert not yet due for renewal
2021-05-18T05:42:40.793480689Z
2021-05-18T05:42:40.793504433Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:40.793512838Z Processing /etc/letsencrypt/renewal/domain2.conf
2021-05-18T05:42:40.793520513Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:41.021487294Z Cert not yet due for renewal
2021-05-18T05:42:41.023566163Z
2021-05-18T05:42:41.023590539Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:41.023617699Z Processing /etc/letsencrypt/renewal/domain3.conf
2021-05-18T05:42:41.023622367Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:41.241812469Z Cert not yet due for renewal
2021-05-18T05:42:41.243426237Z
2021-05-18T05:42:41.243451854Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:41.243460320Z
2021-05-18T05:42:41.243467433Z The following certs are not due for renewal yet:
2021-05-18T05:42:41.243475448Z   /etc/letsencrypt/live/domain1/fullchain.pem expires on 2021-08-10 (skipped)
2021-05-18T05:42:41.243482171Z   /etc/letsencrypt/live/domain2/fullchain.pem expires on 2021-06-18 (skipped)
2021-05-18T05:42:41.243488502Z   /etc/letsencrypt/live/domain3/fullchain.pem expires on 2021-06-18 (skipped)
2021-05-18T05:42:41.243494804Z No renewals were attempted.
2021-05-18T05:42:41.243500715Z No hooks were run.
2021-05-18T05:42:41.243506626Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T05:42:41.354647188Z ----------
2021-05-18T12:00:00.998075033Z 2021-05-18 12:00:00 93e08b32bd47 dnsrobocert.core.main[1] INFO Automated execution: renew certificates if needed.
2021-05-18T12:00:00.998134703Z 2021-05-18 12:00:00 93e08b32bd47 dnsrobocert.core.main[1] INFO Random wait for this execution: 5334 seconds
2021-05-18T13:28:55.148027683Z 2021-05-18 13:28:55 93e08b32bd47 dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python -m dnsrobocert.core.certbot renew -n --user-agent-comment DNSroboCert/3.8.3 --config-dir /etc/letsencrypt --deploy-hook "/usr/local/bin/python -m dnsrobocert.core.hooks -t deploy -c \"/tmp/tmpx3yq_f19/dnsrobocert-runtime.yml\"" --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs
2021-05-18T13:28:55.148052259Z ----------
2021-05-18T13:28:56.298594332Z Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2021-05-18T13:28:56.299526598Z
2021-05-18T13:28:56.299539783Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:56.299549030Z Processing /etc/letsencrypt/renewal/domain1.conf
2021-05-18T13:28:56.299557516Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:56.300354311Z Attempting to parse the version 1.13.0 renewal configuration file found at /etc/letsencrypt/renewal/domain1.conf with version 1.10.1 of Certbot. This might not work.
2021-05-18T13:28:56.589332728Z Cert not yet due for renewal
2021-05-18T13:28:56.590277648Z
2021-05-18T13:28:56.590301001Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:56.590310328Z Processing /etc/letsencrypt/renewal/domain2.conf
2021-05-18T13:28:56.590319465Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:56.808395792Z Cert not yet due for renewal
2021-05-18T13:28:56.811131027Z
2021-05-18T13:28:56.811180819Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:56.811189264Z Processing /etc/letsencrypt/renewal/domain3.conf
2021-05-18T13:28:56.811196688Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:57.043177091Z Cert not yet due for renewal
2021-05-18T13:28:57.044752438Z
2021-05-18T13:28:57.044779478Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:57.044789837Z
2021-05-18T13:28:57.044798223Z The following certs are not due for renewal yet:
2021-05-18T13:28:57.044806388Z   /etc/letsencrypt/live/domain1/fullchain.pem expires on 2021-08-10 (skipped)
2021-05-18T13:28:57.044814383Z   /etc/letsencrypt/live/domain2/fullchain.pem expires on 2021-06-18 (skipped)
2021-05-18T13:28:57.044822698Z   /etc/letsencrypt/live/domain3/fullchain.pem expires on 2021-06-18 (skipped)
2021-05-18T13:28:57.044830473Z No renewals were attempted.
2021-05-18T13:28:57.044837716Z No hooks were run.
2021-05-18T13:28:57.044844909Z - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-05-18T13:28:57.159003690Z ----------
```

**Comment by adferrand** [comment]
Hello! I will look at this problem as soon as possible, most likely this week end.

**Comment by JanickGers85** [comment]
Hello @adferrand , news about this issue?

**Comment by Vertganti** [comment]
From looking a bit at the code I think the issue is that [only the scheduled run at 12:00 passes a `stop_thead`](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/background.py#L25) while [the scheduled run at 0:00 does not](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/background.py#L31) (causing the latter to raise this Error). That part of the code was changed in commit [6abf88b3c065897c15b1296619379a18ef7cb922](https://github.com/adferrand/dnsrobocert/commit/6abf88b3c065897c15b1296619379a18ef7cb922#diff-2147b7f69052ab19138a00679b6e45331a104bb28069227ee57d94736aeb1c4f) and it seems you simply forgot to add the argument to the second run. I can create a quick PR for the fix (copying the line with the GitHub editor) if it is OK that I cannot test it.

**Comment by JanickGers85** [comment]
@adferrand Have you seen that comment of @Vertganti?
I think he got the problem

**Comment by adferrand** [comment]
Indeed, it is the problem. Thanks a lot @Vertganti. @JanickGers85 I am fixing the code and preparing a new release to fix the issue.

**Comment by JanickGers85** [comment]
@adferrand Problem fixed! Thank you!
